[theme]
primaryColor="#FF6347"  # Terra Cotta, bright enough to stand out against dark backgrounds
backgroundColor="#0e1117"  # Deep dark blue-gray, providing a subtle, professional aesthetic
secondaryBackgroundColor="#1a1d23"  # Slightly lighter shade of dark gray to maintain depth
textColor="#E0E0E0"  # Soft white, provides good readability without being too harsh
font="sans serif"  # Continues with a modern and readable font choice

[server]
maxUploadSize = 2048
